#!/bin/sh

source ./config

oops() {
    echo "$0:" "$@" >&2
    exit 1
}

[ -e $local_hashscript ] || oops "no local hashscript found at ${local_hashscript}. Run update_print_hashes to generate the file."

# use the frankenstein print_hashes to get the two variables we need for the
# system that this script is being run on
system=$($local_hashscript system)
hash=$($local_hashscript)

# fetch the tarball
tarball="$tmpdir/nix-${nix_version}-${system}.tar.xz"
wget "https://releases.nixos.org/nix/nix-2.13.3/nix-${nix_version}-${system}.tar.xz" \
    -O $tarball

# compare hashes
actual_hash="$(sha256sum -b "$tarball" | cut -c1-64)"
if [ "$hash" != "$actual_hash" ]; then
    oops "SHA-256 hash mismatch; expected $hash, got $hash2"
fi

# unpack tarball
unpack=$tmpdir/unpack
mkdir -p "$unpack"
tar -xJf "$tarball" -C "$unpack" || oops "failed to unpack '$url'"

rm -f $link
ln -sf $tmpdir/unpack $link
