#!/bin/sh

hashscript=./print_hashes

# use the frankenstein print_hashes to get the two variables we need for the
# system that this script is being run on
system=$($hashscript system)
hash=$($hashscript)

# fetch the tarball
tarball="$tmpdir/nix-${nix_version}-${system}.tar.xz"
wget "https://releases.nixos.org/nix/nix-2.13.3/nix-${nix_version}-${system}.tar.xz" \
    -O $tarball

# compare hashes
actual_hash="$(sha256sum -b "$tarball" | cut -c1-64)"
if [ "$hash" != "$actual_hash" ]; then
    oops "SHA-256 hash mismatch; expected $hash, got $hash2"
fi

# unpack tarball
unpack=$tmpdir/unpack
mkdir -p "$unpack"
tar -xJf "$tarball" -C "$unpack" || oops "failed to unpack '$url'"

script=$(echo "$unpack"/*/install)

[ -e "$script" ] || oops "installation script is missing from the binary tarball!"

echo $tmpdir/unpack
