#!/bin/sh

source ./config

oops() {
    echo "$0:" "$@" >&2
    exit 1
}
target=

if [ $install_in_tmpdir == "yes" ]; then
    target=$(mktemp -d)
else
    target=$install_dir
    mkdir -p $install_dir
fi

[ -e $local_hashscript ] || oops "no local hashscript found at ${local_hashscript}. Run update_print_hashes to generate the file."

# use the frankenstein print_hashes to get the two variables we need for the
# system that this script is being run on
system=$($local_hashscript system)
hash=$($local_hashscript)

# fetch the tarball
tarball="$target/nix-${nix_version}-${system}.tar.xz"
wget "https://releases.nixos.org/nix/nix-2.13.3/nix-${nix_version}-${system}.tar.xz" \
    -O $tarball

# compare hashes
actual_hash="$(sha256sum -b "$tarball" | cut -c1-64)"
if [ "$hash" != "$actual_hash" ]; then
    oops "SHA-256 hash mismatch; expected $hash, got $hash2"
fi

# unpack tarball
unpack=$target/unpack
mkdir -p "$unpack"
tar -xJf "$tarball" -C "$unpack" || oops "failed to unpack '$url'"

rm -f $link
source=$(ls $target/unpack/nix*)
[ -e $source ] || oops "$source doesn't exist."
ln -sf $source $link
