#!/bin/sh

source ./config

tmpdir=$(mktemp -d)
hashscript=$tmpdir/print_hashes
nix_version="2.13.3"

curl -L https://nixos.org/nix/install > $tmpdir/installer

# the nixos installer script contains one case statement which defines some
# variables regarding the hashes and urls of the tarballs
case_linenumber=$(nl -n ln $tmpdir/installer | grep -n 'case' | sed -E -e "s/(^[0-9]*).*?/\1/")
esac_linenumber=$(nl -n ln $tmpdir/installer | grep -n 'esac' | sed -E -e "s/(^[0-9]*).*?/\1/")

# frankenstein together a script which will print the information we need

cat <<EOF > $hashscript

hash=
system=

EOF

sed -n "${case_linenumber},${esac_linenumber}p;" $tmpdir/installer >> $hashscript

cat <<EOF >> $hashscript

if [ "\$1" == "system" ]; then
    echo \$system
else
    echo \$hash
fi

EOF

chmod +x $hashscript

mv $hashscript $local_hashscript
