#!/bin/sh

set -e

current_directory=./stages

# stage one as user (nobody)
unshare --fork --user --mount $current_directory/2_download_hashed_tarball

# bind mount as root
$current_directory/1_bind_mount

# test that everything was set up correctly
unshare --fork --user --mount $current_directory/3_assurances

# begin install
echo "performing a single-user installation of Nix..." >&2
$current_directory/4_load_db

cat >&2 <<EOF

Installation finished!  To ensure that the necessary environment
variables are set, type one of the following, depending on which shell you
are using:

. nix_environment_bash
. nix_environment_zsh
. nix_environment_fish

EOF
